DELETE FROM autor WHERE autor_id = 1; -- ERROR

CREATE TABLE libro(
  libro_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  titulo VARCHAR(30) NOT NULL,
  autor_id INT UNSIGNED NOT NULL,
  descripcion VARCHAR(250)
  FOREIGN KEY(autor_id) REFERENCES autor(autor_id) ON DELETE CASCADE
);

ALTER TABLE libro ADD FOREIGN KEY REFERENCES autor(autor_id) ON DELETE CASCADE;
